# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:58
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ayudante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('paralelo', models.IntegerField()),
                ('aula', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AyudanteTareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('paralelo', models.IntegerField()),
                ('aula', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ayudantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miercoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes')], max_length=3)),
                ('horaInicio', models.TimeField()),
                ('horaFin', models.TimeField()),
                ('aula', models.CharField(max_length=10)),
                ('edificio', models.CharField(max_length=10)),
                ('mapa', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('semana', models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('clase', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('video', models.BooleanField()),
                ('linkVideo', models.URLField()),
                ('diapositiva', models.BooleanField()),
                ('linkDiapositiva', models.FileField(upload_to=b'')),
                ('lectura', models.BooleanField()),
                ('linkLectura', models.FileField(upload_to=b'')),
                ('linkCap', models.FileField(upload_to=b'')),
                ('controlLectura', models.BooleanField()),
                ('leccion', models.BooleanField()),
                ('taller', models.BooleanField()),
                ('deber', models.BooleanField()),
                ('proyecto', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CoRequisito',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('paralelo', models.IntegerField()),
                ('oficina', models.CharField(max_length=20)),
                ('coordinador', models.BooleanField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('DES', 'Descripcion'), ('SYL', 'Syllabus'), ('POL', 'Politicas')], max_length=3, unique=True)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
