# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20170301_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudantia',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10),
        ),
    ]
