# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 18:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20170301_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
