# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
