# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20170301_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
