# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20170301_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudantia',
            name='ayudante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Ayudante'),
        ),
    ]
