# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20170301_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='linkCap',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='clase',
            name='linkDiapositiva',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='clase',
            name='linkLectura',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
