# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20170301_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='linkDiapositiva',
            field=models.FileField(blank=True, upload_to='diapositivas/'),
        ),
    ]
